### ISSUE TITLE
How to handle click events and get the selected value from RadioGroup?

### ISSUE THREAD

**Issue by jlvihv** [thaw-ui/thaw#157]
Hello thaw developers,

I'm having an issue when trying to use the RadioGroup component. I want to capture the selected value when the user clicks on a radio button. However, using the on:input and on:change event handlers doesn't seem to respond correctly to user clicks. On the other hand, trying to use on:click raises a error.

error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at passStringToWasm0 (textool.js:87:31)
    at imports.wbg.__wbg_value_47fe6384562f52ab (textool.js:865:14)
    at textool.wasm.web_sys::features::gen_HtmlInputElement::HtmlInputElement::value::h53599739e637161c (textool.wasm:0x94d1e1)
    at textool.wasm.leptos_dom::helpers::event_target_value::h4e39af179910b487 (textool.wasm:0x964d73)
    at textool.wasm.textool::app::__CaseConversion::{{closure}}::hfebe87d48516690c (textool.wasm:0x6c0998)
    at textool.wasm.leptos_dom::View::on::{{closure}}::hfbd0b2190cbd5bc5 (textool.wasm:0x875c8c)
    at textool.wasm.<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h42e0bd424d71107f (textool.wasm:0x9e04b3)
    at textool.wasm.leptos_dom::View::on_impl::{{closure}}::{{closure}}::he1ee3d60d98b0b72 (textool.wasm:0x8ed38f)
    at textool.wasm.<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::hc89799fdd9d2e24e (textool.wasm:0xa0721d)
    at textool.wasm.leptos_dom::View::on::{{closure}}::h423cdef1c1edf72d (textool.wasm:0x876a68)
```

**Comment by luoxiaozero** [comment]
RadioGroup does not yet support these events, you can get the latest values in the following way:

```rust
    create_effect(move |prev| {
        if prev.is_some() {
            let value = radio_value.get();
            ///
        }
    });
```

**Comment by jlvihv** [comment]
okay, thank you
